name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    code_analysis:
        uses: rectorphp/reusable-workflows/.github/workflows/code_analysis.yaml@main
