name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        uses: rectorphp/reusable-workflows/.github/workflows/code_analysis.yaml@main

    rector:
        # run only on PR's from branches on main repository (from core contributors), not on the forks or PR's from forks.
        if: github.event.pull_request.head.repo.full_name == github.repository

        # see https://github.com/rectorphp/reusable-workflows
        uses: rectorphp/reusable-workflows/.github/workflows/rector.yaml@main
